FROM node:25-alpine
WORKDIR /app

RUN npm install -g pm2
EXPOSE 3000 3001

COPY front.tar.gz ./front.tar.gz

RUN tar -xzf front.tar.gz -C /app && rm -f front.tar.gz

CMD ["pm2-runtime", "start", "ecosystem.json"]
